--- 
- hosts: centos01
  tasks: 
    - name: "Register Output"
      command: hostname -s 
      register: hostname_output
    - name: Display the registered Output
      debug:
        var: hostname_output.stdout

    
   
...