--- 
- hosts: centos01, ubuntu01
  tasks: 
    - name: "Register Output"
      command: hostname -s
      when: 
      	- ansible_distribution == "CentOS"
      	- ansible_distribution_major_version | int >= 7
...