--- 
- hosts: "centos01, ubuntu01"
  tasks: 
    - command: "hostname -s"
      name: "Register Output"
      when: 
        - "ansible_distribution == \"CentOS\""
        - "ansible_distribution_major_version | int >= 7"
...