--- 
- hosts: "centos01, ubuntu01"
  tasks: 
    - command: "hostname -s"
      name: "Register Output"
      when: 
        - "ansible_distribution == \"CentOS\""
        - "ansible_distribution_major_version | int >= 7"
      register: host_output
    - name: display Output when changed 
      debug:
        msg: paramter is changed
      when: host_output is changed
...