#### Testing Hostvars
# Target
- hosts: controlhost
  become: true
  gather_facts: true

  tasks:
    - name: Testiing Hostvars without defalut
      debug:
        msg: "{{ hostvars[ansible_nodename].ansible_port | default('')}}"

    - name: Testiing Hostvars with defalut
      debug:
        msg: "{{ hostvars[ansible_nodename].ansible_port | default('22')}}"