#### Testing Hostvars
# Target
- hosts: control
  become: true
  gather_facts: true

  tasks:
    - name: Testiing Hostvars with defalut empty string
      debug:
        msg: "{{ hostvars[ansible_nodename].ansible_port | default('22')}}"

    - name: Testiing group vars 
      debug:
        msg: "{{ user_name }}"