---
# Target
- hosts: linux
  become: true
  gather_facts: false
# Tasks
  tasks:
   - name: configure MOTD
     copy:
       content: This is for Copy Module with content
       dest: /etc/motd
   

# Handlers

...