---
# Target
- hosts: centos01
  become: true
  gather_facts: false
  vars:
    motd_vars: This is for Copy Module with content changed
# Tasks
  tasks:
   - name: configure MOTD
     copy:
       content: "{{ motd_vars }}"
       dest: /etc/motd
     notify: MOTD Notification
  handlers:
    - name: MOTD Notification
      debug:
        msg: MSG received
    - name: LinkNotify
      debug:
        msg: LinkNotification received
   

# Handlers

...