---
# Target
- hosts: centos01
  become: true
  gather_facts: true
  vars:
    motd_centos: This is for handler testing for centos
    motd_ubuntu: This is for handler testing for ubuntu
# Tasks
  tasks:
   - name: configure MOTD for CentOs
     copy:
       content: "{{ motd_centos }}"
       dest: /etc/motd
     notify: MOTDCentos
     when: ansible_distribution == "CentOs"
   - name: configure MOTD for ubuntu
     copy:
       content: "{{ motd_ubuntu }}"
       dest: /etc/motd
     notify: MOTDUbuntu
     when: ansible_distribution == "Ubuntu"

  handlers:
    - name: MOTDCentos
      debug:
        msg: MSG received for CentOs
    - name: MOTDUbuntu
      debug:
        msg: LinkNotification received for ubuntu
   

# Handlers

...