- hosts: centos01, ubuntu01

# Tasks
  tasks:
   - name: configure MOTD for CentOs
     copy:
       content: "welcome to {{ item }} Linux" 
       dest: /etc/motd
     with_items: ['CentOS', 'Ubuntu']
     when: ansible_distribution == item 