# This is for if else if statement
- hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: jinja2 example for if else if statement
      debug:
        msg: >
             ----== If the hostname is control print a message==---
             {# This is the comment line-#}
             {% if ansible_hostname == "ansible-controlhost1" -%}
                  This is the control host
             {% elseif ansible_hostname == centos01 -%}
                  This belongs to Redhat family
             {% endif %}
