# for loop with range parameter
- hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: jinja2 example for for loop with range
      debug:
        msg: >
             The values in the array are,
             {# This is the comment line-#}
             {% for item in range(1,11) -%}
             {{item}}
             {% endfor %}