---
- hosts: control
  become: true
  gather_facts: true

  tasks:
    - name: Gathering facts ip address
      debug:
        msg: "{{ ansible_default_ipv4.address }}"
      debug:
        msg: "{{ appa | default(30) }}"
      debug:
        msg: "{{ lookup('env', 'makireddy') | default('chicago', true) }}"
#if the env variable is not defined, it prints nothing but doesn't throw error
    - file:
        dest: "{{ item.path }}"
        state: touch
        mode: "{{ item.mode | default(omit) }}"
      loop:
        - path: /tmp/demofilter
        - path: /tmp/test
          mode: "0600"
      debug:
        msg: "{{ [1,2,3,4,5] | min }}"
        msg: "{{ [1,2,3,4,5] | max }}"
        msg: "{{ [1,2,3,4,5,1,2,6] | unique }}"
        msg: "{{ [1,2,3,4,5,1,2,6] | unique | to_yaml }}"
...

