--- 
- hosts: linux:!ubuntu01!centos01
  tasks: 
    - name: "set FACT"
      set_fact: 
        sd_fact: "This is my first FACT"
    - debug: 
        msg: "{{ sd_fact }}"
      name: "display FACT"
...