--- 
- hosts: linux
  tasks: 
    - name: "set FACT"
      set_fact: 
        sd_web_path: /usr/share/www
      when: ansible_distribution == "CentOS"
    - name: "set FACT"
      set_fact: 
        sd_web_path: /var/www/html
      when: ansible_distribution == "Ubuntu"
    - name: "disply FACT"
    - debug: 
        msg: "{{ sd_web_path }}"
   
...